-- ============================================================================
-- nina_tennis — serverless (Supabase Postgres)
-- Миграция 0001: схема, индексы, RLS, view, realtime
-- Перенос Mongoose-схем (apps/backend) в реляционные таблицы.
-- ============================================================================
-- Примечания по дизайну:
--  * profiles.id — uuid; соответствует потенциальной интеграции с Supabase Auth
--    (auth.users.id = uuid). Сейчас auth — собственный (bcrypt) поверх next-auth,
--    но структура совместима с будущим переходом на нативный Supabase Auth.
--  * club у игроков — текст (как в Mongo), без FK — сохраняем совместимость с UI.
--  * judgedBy (массив в Mongo) → отдельная таблица match_judges.
--  * RLS: публичный SELECT, запись — только через service_role (Server Actions).
--    Браузерный anon-клиент читает данные напрямую (serverless-стиль + Realtime).
-- ============================================================================

-- ----------------------------------------------------------------------------
-- profiles (бывшая коллекция users)
-- ----------------------------------------------------------------------------
create table if not exists public.profiles (
  id            uuid primary key default gen_random_uuid(),
  email         text not null unique,
  password_hash text not null,
  role          text not null default 'user' check (role in ('admin','user','referee')),
  first_name    text,
  last_name     text,
  created_at    timestamptz not null default now()
);

comment on table public.profiles is 'Пользователи системы (связано с auth, но НЕ с Supabase Auth — свой bcrypt)';

-- ----------------------------------------------------------------------------
-- clubs
-- ----------------------------------------------------------------------------
create table if not exists public.clubs (
  id   bigint generated by default as identity primary key,
  name text not null unique
);

-- ----------------------------------------------------------------------------
-- players
-- ----------------------------------------------------------------------------
create table if not exists public.players (
  id         bigint generated by default as identity primary key,
  full_name  text not null,
  birth_year int,
  gender     char(1) check (gender in ('М','Ж')),
  club       text,                 -- строка, как в Mongo (без FK)
  photo_url  text,
  rating     int
);

comment on column public.players.club is 'Название клуба текстом (без FK) — совместимость с UI';

-- ----------------------------------------------------------------------------
-- tournaments
-- ----------------------------------------------------------------------------
create table if not exists public.tournaments (
  id                    bigint generated by default as identity primary key,
  name                  text not null,
  start_date            timestamptz,
  end_date              timestamptz,
  club_id               bigint references public.clubs(id) on delete set null,
  referee_invite_token  text,
  created_at            timestamptz not null default now()
);

create index if not exists idx_tournaments_club on public.tournaments(club_id);
create index if not exists idx_tournaments_invite_token on public.tournaments(referee_invite_token);

-- ----------------------------------------------------------------------------
-- groups
-- Связь group ↔ tournament теперь через FK (раньше — массив в tournament.groups).
-- Допускаем null на турнир: старый код разрешал группы без турнира.
-- ----------------------------------------------------------------------------
create table if not exists public.groups (
  id            bigint generated by default as identity primary key,
  name          text not null,
  tournament_id bigint references public.tournaments(id) on delete cascade
);

create index if not exists idx_groups_tournament on public.groups(tournament_id);

-- ----------------------------------------------------------------------------
-- group_players (M:N — бывший массив group.players)
-- ----------------------------------------------------------------------------
create table if not exists public.group_players (
  group_id  bigint not null references public.groups(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete cascade,
  primary key (group_id, player_id)
);

create index if not exists idx_group_players_player on public.group_players(player_id);

-- ----------------------------------------------------------------------------
-- group_seeds (посев — бывший embedded seededPlayers[])
-- ----------------------------------------------------------------------------
create table if not exists public.group_seeds (
  group_id  bigint not null references public.groups(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete cascade,
  seed      int not null,
  primary key (group_id, player_id)
);

create index if not exists idx_group_seeds_group on public.group_seeds(group_id);

-- ----------------------------------------------------------------------------
-- tournament_referees (M:N судей — бывший массив tournament.referees)
-- ----------------------------------------------------------------------------
create table if not exists public.tournament_referees (
  tournament_id bigint not null references public.tournaments(id) on delete cascade,
  user_id       uuid  not null references public.profiles(id) on delete cascade,
  primary key (tournament_id, user_id)
);

create index if not exists idx_tournament_referees_user on public.tournament_referees(user_id);

-- ----------------------------------------------------------------------------
-- matches
-- scoring_state — jsonb (полный снимок состояния скоринга).
-- point_history — int[] (стороны 1/2 для undo).
-- court_side разложен в скаляры p1/p2 (в Mongo был вложенный объект).
-- ----------------------------------------------------------------------------
create table if not exists public.matches (
  id             bigint generated by default as identity primary key,
  group_id       bigint references public.groups(id) on delete cascade,
  player1_id     bigint references public.players(id) on delete set null,
  player2_id     bigint references public.players(id) on delete set null,
  score          text,
  status         text not null default 'scheduled' check (status in ('scheduled','in_progress','finished','canceled')),
  scheduled_at   timestamptz,
  played_at      timestamptz,
  winner_id      bigint references public.players(id) on delete set null,
  court          text not null default '',
  round          int,
  server_side    text check (server_side in ('left','right')),
  court_side_p1  text check (court_side_p1 in ('left','right')),
  court_side_p2  text check (court_side_p2 in ('left','right')),
  scoring_state  jsonb,
  point_history  int[] not null default '{}',
  referee_id     uuid references public.profiles(id) on delete set null,
  created_at     timestamptz not null default now()
);

create index if not exists idx_matches_group   on public.matches(group_id);
create index if not exists idx_matches_round    on public.matches(round);
create index if not exists idx_matches_referee  on public.matches(referee_id);
create index if not exists idx_matches_status   on public.matches(status);
create index if not exists idx_matches_winner   on public.matches(winner_id);

-- ----------------------------------------------------------------------------
-- match_judges (история судей матча — бывший массив match.judgedBy)
-- ----------------------------------------------------------------------------
create table if not exists public.match_judges (
  match_id  bigint not null references public.matches(id) on delete cascade,
  user_id   uuid  not null references public.profiles(id) on delete cascade,
  judged_at timestamptz not null default now(),
  primary key (match_id, user_id)
);

create index if not exists idx_match_judges_user on public.match_judges(user_id);

-- ============================================================================
-- VIEW: v_matches_full — матч + игроки + судья + группа + турнир
-- Заменяет Mongo populate([...]) и ручную сборку в TS.
-- ============================================================================
create or replace view public.v_matches_full as
select
  m.id, m.group_id, m.player1_id, m.player2_id, m.score, m.status,
  m.scheduled_at, m.played_at, m.winner_id, m.court, m.round,
  m.server_side, m.court_side_p1, m.court_side_p2,
  m.scoring_state, m.point_history, m.referee_id, m.created_at,
  g.name     as group_name,
  g.tournament_id,
  p1.full_name as player1_name, p1.photo_url as player1_photo, p1.club as player1_club,
  p2.full_name as player2_name, p2.photo_url as player2_photo, p2.club as player2_club,
  ref.email    as referee_email,
  ref.first_name as referee_first_name,
  ref.last_name  as referee_last_name
from public.matches m
left join public.groups   g  on g.id = m.group_id
left join public.players  p1 on p1.id = m.player1_id
left join public.players  p2 on p2.id = m.player2_id
left join public.profiles ref on ref.id = m.referee_id;

comment on view public.v_matches_full is 'Матч со связями (игроки, судья, группа) — замена Mongo populate';

-- ============================================================================
-- Row Level Security
-- Политика: SELECT открыт для anon/auth (публичные данные турниров/табло).
-- Запись — только через service_role (Server Actions). Обычный клиент не пишет.
-- ============================================================================
alter table public.profiles            enable row level security;
alter table public.clubs               enable row level security;
alter table public.players             enable row level security;
alter table public.tournaments         enable row level security;
alter table public.groups              enable row level security;
alter table public.group_players       enable row level security;
alter table public.group_seeds         enable row level security;
alter table public.tournament_referees enable row level security;
alter table public.matches             enable row level security;
alter table public.match_judges        enable row level security;

-- Профиль: пользователь видит только себя (по email из JWT next-auth читать не можем
-- на уровне RLS, поэтому профиль отдаём через Server Action). Аномymous не видит.
create policy "profiles_self_read" on public.profiles
  for select using (false);  -- чтение профилей идёт через service_role в Server Actions

-- Остальные таблицы: публичный read (турниры, сетки, игроки, матчи — публичный сайт).
create policy "clubs_public_read" on public.clubs
  for select using (true);

create policy "players_public_read" on public.players
  for select using (true);

create policy "tournaments_public_read" on public.tournaments
  for select using (true);

create policy "groups_public_read" on public.groups
  for select using (true);

create policy "group_players_public_read" on public.group_players
  for select using (true);

create policy "group_seeds_public_read" on public.group_seeds
  for select using (true);

create policy "tournament_referees_public_read" on public.tournament_referees
  for select using (true);

create policy "matches_public_read" on public.matches
  for select using (true);

create policy "match_judges_public_read" on public.match_judges
  for select using (true);

-- NOTE: политики INSERT/UPDATE/DELETE намеренно отсутствуют для anon/authenticated.
-- Все мутации выполняются с service_role ключом (bypass RLS) в Server Actions,
-- где роли проверяются серверным кодом (см. app/lib/permissions.ts).

-- ============================================================================
-- RPC: can_user_judge_match — может ли пользователь судить матч.
-- Замена TournamentsService.assertCanJudgeMatch одним SQL-запросом.
-- Возвращает true для admin; для referee — если он в tournament_referees
-- турнира этого матча (match → group → tournament → referees).
-- ============================================================================
create or replace function public.can_user_judge_match(p_match_id bigint, p_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.matches m
    join public.groups g               on g.id = m.group_id
    join public.tournaments t          on t.id = g.tournament_id
    join public.tournament_referees tr on tr.tournament_id = t.id
    where m.id = p_match_id
      and tr.user_id = p_user_id
  )
    or exists (
      -- admin судит любой матч
      select 1 from public.profiles
      where id = p_user_id and role = 'admin'
    );
$$;

comment on function public.can_user_judge_match is 'Может ли пользователь судить матч (admin — всегда; referee — если он в судьях турнира)';

-- ============================================================================
-- Storage: bucket для аватаров игроков (публичное чтение).
-- Замена player_photos/ как статики в NestJS.
-- ============================================================================
insert into storage.buckets (id, name, public)
values ('player-avatars', 'player-avatars', true)
on conflict (id) do nothing;

-- Политика: запись только авторизованным (RLS Storage). Чтение публичное (bucket public=true).
create policy "player_avatars_public_read" on storage.objects
  for select using (bucket_id = 'player-avatars');

create policy "player_avatars_authed_write" on storage.objects
  for insert to authenticated with check (bucket_id = 'player-avatars');

create policy "player_avatars_authed_update" on storage.objects
  for update to authenticated using (bucket_id = 'player-avatars');

create policy "player_avatars_authed_delete" on storage.objects
  for delete to authenticated using (bucket_id = 'player-avatars');

-- ============================================================================
-- Realtime: включаем публикацию таблиц для live-обновлений
-- ============================================================================
alter publication supabase_realtime add table public.matches;
alter publication supabase_realtime add table public.match_judges;
